
//Create a server
//1. Import http module, 2.Create a server with the imported http module bu passing a function, which takes request and response as parameters
//A request is generated by node js for us and a response is what we would like to send back to client
const express  = require('express');
const bodyParser = require('body-parser');
const path = require('path');

const app = express();

const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');

app.use(bodyParser.urlencoded({extended:false}));
app.use(express.static(path.join(__dirname,'public'))); // gives readonly access to public folder

app.use(shopRoutes);
app.use('/admin',adminRoutes);

app.use((req,res,next) =>{
    res.status(404).sendFile(path.join(__dirname,'views','404.html'));
})

app.listen(3050, () => {
    console.log("Server running in port 3050");
});
